### ISSUE TITLE
Does wasm plugin support static configuration?

### ISSUE THREAD

**Issue by jcchavezs** [intel/modsecurity-wasm-filter#6]
Currently I am trying to build an e2e for the filter (see https://github.com/jcchavezs/modsecurity-wasm-filter-e2e). Right now I am struggling to get rules to work declared statically (with no ruleserver, plain envoy), I tried this configuration

```
                http_filters:
                  - name: envoy.filters.http.wasm
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      config:
                        name: "my_plugin"
                        root_id: "my_root_id"
                        configuration:
                          "@type": "type.googleapis.com/google.protobuf.StringValue"
                          value: |
                            SecDebugLogLevel 5
                            SecDebugLog modsec.log
                            SecRuleEngine On
                            SecRule REQUEST_URI "@streq /admin" "id:1,phase:1,t:lowercase,deny"
                        vm_config:
                          runtime: "envoy.wasm.runtime.v8"
                          vm_id: "my_vm_id"
                          configuration: {}
                          code:
                            local:
                              filename: ./bin/modsecurity-filter.wasm
```

and this configuration

```
                http_filters:
                  - name: envoy.filters.http.wasm
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      config:
                        name: "my_plugin"
                        root_id: "my_root_id"
                        configuration:
                          "@type": "type.googleapis.com/google.protobuf.StringValue"
                          value: |
                            {
                              "rules_inline" : "
                                SecDebugLogLevel 5
                                SecDebugLog modsec.log
                                SecRuleEngine On
                                SecRule REQUEST_URI \"@streq /admin\" \"id:1,phase:1,t:lowercase,deny\"
                              "
                            }
                        vm_config:
                          runtime: "envoy.wasm.runtime.v8"
                          vm_id: "my_vm_id"
                          configuration: {}
                          code:
                            local:
                              filename: ./bin/modsecurity-filter.wasm
```

But I don't get to block the request. Is there anything I am doing wrong?

You can reproduce my e2e test following the instructions of this repository: https://github.com/jcchavezs/modsecurity-wasm-filter-e2e
